version: "3.9"

services:
  gouache-resource:
    container_name: gouache-resource
    restart: always
    ports:
      - "5000:5000"
    build:
      context: ./services/resource/
      dockerfile: Dockerfile.dev
    env_file: ./services/resource/.env
    volumes:
      - ./services/resource/:/app
    networks:
      - gouache-network
    depends_on:
      - gouache-db
      - gouache-cache

  gouache-session:
    container_name: gouache-session
    restart: always
    ports:
      - "4000:4000"
    build:
      context: ./services/session/
      dockerfile: Dockerfile.dev
    networks:
      - gouache-network
    depends_on:
      - gouache-dynamodb

  gouache-db:
    container_name: gouache-db
    image: 'postgres:latest'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    networks:
      - gouache-network
    volumes:
      - ./services/db/:/docker-entrypoint-initdb.d/
      # - ./db-data/:/var/lib/postgresql/data/

  gouache-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: gouache-dynamodb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data" # dirty fix: sudo chmod 777 ./docker/dynamodb
    working_dir: /home/dynamodblocal

  gouache-cache:
    container_name: gouache-cache
    image: redis
    restart: always
    ports:
     - "6379:6379"
    networks:
      - gouache-network
    command: redis-server --save 20 1 --loglevel warning --requirepass password

  gouache-client:
    container_name: gouache-client
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./services/client/
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/client/.env
    volumes:
      - ./services/client/:/app
    networks:
      - gouache-network
    depends_on:
      - gouache-resource


networks:
  gouache-network:
    driver: bridge
