version: "3.9"

services:
  gouache-api:
    container_name: gouache-api
    restart: always
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - gouache-network

networks:
  gouache-network:
    driver: bridge
