version: "3.9"

services:
  gouache-api:
    container_name: gouache-api
    restart: always
    ports:
      - "5000:5000"
    build:
      context: ./apps/api/
      dockerfile: Dockerfile.dev
    env_file: ./apps/api/.env
    volumes:
      - ./apps/api/:/app
    networks:
      - gouache-network

  gouache-client:
    container_name: gouache-client
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./apps/client/
      dockerfile: Dockerfile.dev
    env_file:
      - ./apps/client/.env
    volumes:
      - ./apps/client/:/app
    networks:
      - gouache-network
    depends_on:
      - gouache-api


networks:
  gouache-network:
    driver: bridge
