version: "3.9"

services:
  gouache-api:
    container_name: gouache-api
    restart: always
    ports:
      - "5000:5000"
    build:
      context: ./services/api/
      dockerfile: Dockerfile.dev
    env_file: ./services/api/.env
    volumes:
      - ./services/api/:/app
    networks:
      - gouache-network
    depends_on:
      - gouache-db

  gouache-db:
    container_name: gouache-db
    restart: always
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    networks:
      - gouache-network
    volumes:
      - ./services/db/:/docker-entrypoint-initdb.d/
      # - ./db-data/:/var/lib/postgresql/data/

  gouache-client:
    container_name: gouache-client
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./services/client/
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/client/.env
    volumes:
      - ./services/client/:/app
    networks:
      - gouache-network
    depends_on:
      - gouache-api


networks:
  gouache-network:
    driver: bridge
