server:
  port: 4000

spring:
  mvc:
    # prevent requests that would yield a 404 from being forwarded to the default servlet so we can handle ourselves
    throwExceptionIfNoHandlerFound: true
  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false

restart:
  include:
    dynamodb: /dynamodb-[\\w\\d-\.]+\.jar

---
# mvn spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=local"
spring:
  config:
    activate:
      on-profile: local
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://localhost
    port: 8000
    region: us-east-1
  sqs:
    report_queue: report-queue
    host: http://localhost
    port: 9324
    region: elasticmq

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

app:
  locale: resource-local
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: localhost
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: dev
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1
  sqs:
    report_queue: report-queue
    host: http://qouache-queue
    port: 9324
    region: elasticmq

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

app:
  locale: resource-dev
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: qa
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1
  sqs:
    report_queue: report-queue
    host: http://qouache-queue
    port: 9324
    region: elasticmq

app:
  locale: resource-qa
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: prod
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1
  sqs:
    report_queue: report-queue
    host: http://qouache-queue
    port: 9324
    region: elasticmq

app:
  locale: resource-prod
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password
