server:
  port: 4000

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: local
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://localhost
    port: 8000
    region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

app:
  locale: resource-dev
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: localhost
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: dev
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

app:
  locale: resource-dev
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: qa
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1

app:
  locale: resource-qa
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password

---
spring:
  config:
    activate:
      on-profile: prod
  cache-type: redis

aws:
  access_key: QXdzQWNjZXNzS2V5Cg==
  secret_key: QXdzU2VjcmV0S2V5Cg==
  dynamodb:
    host: http://gouache-dynamodb
    port: 8000
    region: us-east-1

app:
  locale: resource-prod
  cookie_name: gouache_session
  client_host: http://localhost
  client_port: 3000
  redis:
    host: gouache-cache
    port: 6379
    password: password
