server:
  port: 4000

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:resourcedb
    driverClassName: org.h2.Driver
    username: mz
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

aws:
  accessKey: "QXdzQWNjZXNzS2V5Cg=="
  secretKey: "QXdzU2VjcmV0S2V5Cg=="
  dynamodb:
    host: "http://localhost"
    port: 8000
    region: "us-central-1"

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

app:
  locale: session-dev

---
spring:
  config:
    activate:
      on-profile: qa

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:resourcedb
    driverClassName: org.h2.Driver
    username: mz
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

aws:
  accessKey: "QXdzQWNjZXNzS2V5Cg=="
  secretKey: "QXdzU2VjcmV0S2V5Cg=="
  dynamodb:
    host: "http://localhost"
    port: 8000
    region: "us-central-1"

app:
  locale: session-qa

---
spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:resourcedb
    driverClassName: org.h2.Driver
    username: mz
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

aws:
  accessKey: "QXdzQWNjZXNzS2V5Cg=="
  secretKey: "QXdzU2VjcmV0S2V5Cg=="
  dynamodb:
    host: "http://localhost"
    port: 8000
    region: "us-central-1"

app:
  locale: session-prod
