#!/bin/bash
SESSION='123'


# add report
add_report() {
  local caller="$1"
  local data="$2"
  local name="$3"

  curl localhost:6000/api/report -d "{\"caller\": \"$caller\", \"data\": \"$data\", \"name\": \"$name\"}" -H 'Content-Type: application/json' --cookie "gouache_session=$SESSION" -v
}

# get report
get_report() {
  local id="$1"

  curl localhost:6000/api/report/$1 --cookie "gouache_session=$SESSION" -v
}

# get all reports
get_all_reports() {
  # curl localhost:6000/api/report?last_page_key=72e372b4-deec-4f08-806e-90e0112d9289 --cookie "gouache_session=$SESSION" -v
  curl localhost:6000/api/report --cookie "gouache_session=$SESSION" -v
}


main () {
  # start redis
  sudo service redis-server start

  # set session
  echo "SET "$SESSION" '{\"Username\":\"user\",\"Expiry\":\"9999-08-29 21:59:59.999999\"}'" | redis-cli

  # start local db
  docker run -p 8000:8000 amazon/dynamodb-local   -jar DynamoDBLocal.jar -sharedDb &

  # create table
  aws dynamodb --endpoint-url http://localhost:8000 --region us-east-1 create-table --table-name report  --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
}

# stop here if being sourced
return 2>/dev/null

# stop on errors and unset variable refs
set -o errexit
set -o nounset

main $*
